// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsmCr3dRWuHkE_KqrExjYjCaEob7iMg6g',
    appId: '1:810598679294:web:18097fabe0a7ab59ac1baf',
    messagingSenderId: '810598679294',
    projectId: 'mygermanfreund',
    authDomain: 'mygermanfreund.firebaseapp.com',
    storageBucket: 'mygermanfreund.firebasestorage.app',
    measurementId: 'G-S20HMTHHJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBIWF6kCTK64qXLcMPFyzmVYsTqnK1ke0',
    appId: '1:810598679294:android:17baae45c1e48113ac1baf',
    messagingSenderId: '810598679294',
    projectId: 'mygermanfreund',
    storageBucket: 'mygermanfreund.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKXoGNFDWoWH1lzYZV8tB4ebU_crLIA0',
    appId: '1:810598679294:ios:1ebbf6a5cdd53125ac1baf',
    messagingSenderId: '810598679294',
    projectId: 'mygermanfreund',
    storageBucket: 'mygermanfreund.firebasestorage.app',
    iosBundleId: 'com.example.mygermanfreund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKXoGNFDWoWH1lzYZV8tB4ebU_crLIA0',
    appId: '1:810598679294:ios:1ebbf6a5cdd53125ac1baf',
    messagingSenderId: '810598679294',
    projectId: 'mygermanfreund',
    storageBucket: 'mygermanfreund.firebasestorage.app',
    iosBundleId: 'com.example.mygermanfreund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsmCr3dRWuHkE_KqrExjYjCaEob7iMg6g',
    appId: '1:810598679294:web:0c89b946277e5a72ac1baf',
    messagingSenderId: '810598679294',
    projectId: 'mygermanfreund',
    authDomain: 'mygermanfreund.firebaseapp.com',
    storageBucket: 'mygermanfreund.firebasestorage.app',
    measurementId: 'G-00L00HDB0J',
  );

}